---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch-project
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: elasticsearch
      sourceRef:
        kind: HelmRepository
        name: mesosphere.github.io-charts-stable
        namespace: kommander-flux
      version: 2.0.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: elasticsearch
  valuesFrom:
    - kind: ConfigMap
      name: elasticsearch-project-2.0.0-d2iq-defaults
  targetNamespace: ${releaseNamespace}
